name: pipeline
on:
  push:
    branches: [ "main"]

env:
  DOCKER_IMAGE: ""

jobs:
  # verificar que existan comentarios en los scripts 
  auditoria:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Verificar existencia de comentarios
        run: |
          if grep -L '^#.*' $(find . -name "*.sh"); then
            echo "Sin comentarios"
            exit 1
          else
            echo "Aprobado"
          fi
  
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/ 
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login en Docker Hub 
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Construir imagen Docker
        run: |
          docker build -t $DOCKER_IMAGE:${{ github.sha }} .
      
      - name: Push imagen Docker
        run: |
          docker push $DOCKER_IMAGE:${{ github.sha }}
  
  # Depende del job de tests
    depends-on:
      - tests